### ISSUE TITLE
HPE OneView 2.00 Missing CMDLETs

### ISSUE THREAD

**Issue by ChrisLynchHPE** [HewlettPackard/POSH-HPOneView#43]
Here is the list of CMDLETs that still need to be updated:

## Todo

- [x] ~~Show-HPOVSSLCertificate~~ {deprecated}

## Done
- [x] Get-HPOVPowerDevice ~~(coming in the v2.0.139.0 release)~~
- [x] Get-HPOVPowerPotentialDeviceConnection ~~(coming in the v2.0.139.0 release)~~
- [x] Get-HPOVScmbCertificates ~~(coming in the v2.0.139.0 release)~~
- [X] Get-HPOVStoragePool ~~~~(coming in the v2.0.67.0 release)~~~~
- [X] Get-HPOVStorageVolumeTemplate ~~(coming in the v2.0.67.0 release)~~
- [X] Get-HPOVStorageVolumeTemplatePolicy ~~(coming in the v2.0.67.0 release)~~
- [x] Get-HPOVUnmanagedDevice ~~(coming in the v2.0.139.0 release)~~
- [x] New-HPOVNetworkSet ~~(coming in the v2.0.139.0 release)~~
- [x] New-HPOVServerProfileAssign ~~(coming in the v2.0.139.0 release)~~
- [X] New-HPOVStorageVolumeTemplate ~~(coming in the v2.0.67.0 release)~~
- [x] New-HPOVUnmanagedDevice ~~(coming in the v2.0.139.0 release)~~
- [x] Remove-HPOVNetworkSet ~~(coming in the v2.0.139.0 release)~~
- [x] Remove-HPOVPowerDevice ~~(coming in the v2.0.139.0 release)~~
- [x] Remove-HPOVSanManager ~~(coming in the v2.0.175.0 release)~~
- [X] Remove-HPOVStoragePool ~~(coming in the v2.0.67.0 release)~~
- [X] Remove-HPOVStorageSystem ~~(coming in the v2.0.67.0 release)~~
- [X] Remove-HPOVStorageVolume ~~(coming in the v2.0.67.0 release)~~
- [X] Remove-HPOVStorageVolumeTemplate ~~(coming in the v2.0.67.0 release)~~
- [x] Remove-HPOVUnmanagedDevice ~~(coming in the v2.0.139.0 release)~~
- [x] Set-HPOVNetworkSet ~~(coming in the v2.0.139.0 release)~~
- [x] Set-HPOVStorageVolume ~~(coming in the v2.0.67.0 release)~~
- [x] Set-HPOVStorageVolumeTemplatePolicy ~~(coming in the v2.0.67.0 release)~~
- [x] Show-HPOVPortStatistics ~~(coming in the v2.0.175.0 release)~~
- [x] Update-HPOVSanManager ~~(coming in the v2.0.175.0 release)~~
- [x] Update-HPOVStorageSystem ~~(coming in the v2.0.175.0 release)~~
- [x] Set-HPOVManagedSan ~~(coming in the v2.0.279.0 release)~~
- [x] Set-HPOVSanManager ~~(coming in the v2.0.279.0 release)~~
- [x] Search-HPOVAssociations (coming in the v2.0.300.0 release)
- [x] Search-HPOVIndex (coming in the v2.0.300.0 release)
- [x] Show-HPOVFirmwareReport (coming in the v2.0.300.0 release)

**Comment by ljohnston11** [comment]
Chris, is there good method to add a network to a network set? and not clear out the existing networks in the network set? Or a way to read existing networks in the set to then compile a file list of networks to include in the network set? and same for uplinks, interconnects and interconnect groups
Thanks, Lee

**Comment by ChrisLynchHP** [comment]
Please use a new issue to ask this question please.
